
services:
  app:
    container_name: blog-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:

      DB_HOST: blog-db
      DB_PORT: 5432
      DB_NAME: blog
      DB_USER: postgres
      DB_PASSWORD: password

  db:
    container_name: blog-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5

volumes:
  db_data: