spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
logging:
  level:
    org.springframework.security: DEBUG