CREATE TABLE IF NOT EXISTS users
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login             VARCHAR(50),
    password          VARCHAR(100),
    email             VARCHAR(50),
    date_registration TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS posts
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(50),
    content     TEXT,
    author_id   INTEGER,
    create_date TIMESTAMP,
    update_date TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     INTEGER,
    author_id   INTEGER,
    content     TEXT,
    create_date TIMESTAMP,
    update_date TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES users (id),
    FOREIGN KEY (post_id) REFERENCES posts (id)
);
