CREATE TABLE IF NOT EXISTS users
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login             VARCHAR(50),
    password          VARCHAR(50),
    email             VARCHAR(50),
    date_registration TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



INSERT INTO users(login, password, email)
VALUES ('Rav', '1234', 'ravv@mail.ru');
INSERT INTO users(login, password, email)
VALUES ('Alisa', '4321', 'alice@gmail.com');

CREATE TABLE IF NOT EXISTS posts
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(50),
    content     TEXT,
    author_id   INTEGER,
    create_date TIMESTAMP,
    update_date TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES users (id)
);

INSERT INTO posts (title, content, author_id, create_date, update_date)
VALUES ('Изучение Spring', 'Как я учил Spring...', 1, '2025-07-30 10:00:00', '2025-07-30 10:00:00');

INSERT INTO posts (title, content, author_id, create_date, update_date)
VALUES ('Изучение Hibernate', 'Как я учил Hibernate...', 1, '2025-07-29 12:00:00', '2025-07-29 13:00:00');

CREATE TABLE IF NOT EXISTS comments
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     INTEGER,
    author_id   INTEGER,
    content     TEXT,
    create_date TIMESTAMP,
    update_date TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES users (id),
    FOREIGN KEY (post_id) REFERENCES posts (id)
);

INSERT INTO comments (post_id, author_id, content, create_date, update_date)
VALUES (1, 2, 'Ну ты балбес', '2025-07-30 15:00:00', '2025-07-30 15:00:00');

INSERT INTO comments (post_id, author_id, content, create_date, update_date)
VALUES (2, 2, 'Уважаемо', '2025-07-30 16:00:00', '2025-07-30 17:00:00');

INSERT INTO comments (post_id, author_id, content, create_date, update_date)
VALUES (1, 1, 'Сам такой', '2025-07-30 17:00:00', '2025-07-30 18:00:00');

CREATE TABLE IF NOT EXISTS roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(50)
);


INSERT INTO roles(role)
VALUES ('admin');
INSERT INTO roles(role)
VALUES ('user');

CREATE TABLE IF NOT EXISTS user_roles
(
    user_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (role_id) REFERENCES roles (id)
);

INSERT INTO user_roles
VALUES (1, 1),
       (1, 2),
       (2, 2),
       (4, 2);


