--liquibase formatted sql

--changeset rav:init_schema

CREATE TABLE IF NOT EXISTS users
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login             VARCHAR(50),
    password          VARCHAR(100),
    email             VARCHAR(50),
    date_registration TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS posts
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(50),
    content     TEXT,
    author_id   INTEGER,
    create_date TIMESTAMP,
    update_date TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     INTEGER,
    author_id   INTEGER,
    content     TEXT,
    create_date TIMESTAMP,
    update_date TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES users (id),
    FOREIGN KEY (post_id) REFERENCES posts (id)
);

INSERT INTO users(login, password, email)
VALUES ('Rav', '1234', 'ravv@mail.ru');

INSERT INTO users(login, password, email)
VALUES ('Alisa', '4321', 'alice@gmail.com');

INSERT INTO posts (title, content, author_id, create_date, update_date)
VALUES ('Изучение Spring', 'Как я учил Spring...', 1, '2025-07-30 10:00:00', '2025-07-30 10:00:00');

INSERT INTO posts (title, content, author_id, create_date, update_date)
VALUES ('Изучение Hibernate', 'Как я учил Hibernate...', 1, '2025-07-29 12:00:00', '2025-07-29 13:00:00');

INSERT INTO comments (post_id, author_id, content, create_date, update_date)
VALUES (1, 2, 'Первый!', '2025-07-30 15:00:00', '2025-07-30 15:00:00');

INSERT INTO comments (post_id, author_id, content, create_date, update_date)
VALUES (1, 1, 'Да уж', '2025-07-30 16:00:00', '2025-07-30 17:00:00');

INSERT INTO comments (post_id, author_id, content, create_date, update_date)
VALUES (2, 1, 'Начинаем', '2025-07-30 17:00:00', '2025-07-30 18:00:00');